### ISSUE TITLE
Site down: staticsitegenerators.net

### ISSUE THREAD

**Issue by lexoyo** [bevry/staticsitegenerators-website#24]
As [reported here](https://github.com/bevry/staticsitegenerators-list/issues/227)

staticsitegenerators.net says

```
An error has occured when parsing the latest static site generators data feed:

YAMLException: duplicated mapping key at line 1829, column 28:
      website: "http://vlv.io/"
                               ^
  at generateError (/home/travis/build/bevry/staticsitegenerators-website/node_modules/feedr/node_modules/js-yaml/lib/js-yaml/loader.js:161:10)
  at throwError (/home/travis/build/bevry/staticsitegenerators-website/node_modules/feedr/node_modules/js-yaml/lib/js-yaml/loader.js:167:9)
  at storeMappingPair (/home/travis/build/bevry/staticsitegenerators-website/node_modules/feedr/node_modules/js-yaml/lib/js-yaml/loader.js:304:7)
  at readBlockMapping (/home/travis/build/bevry/staticsitegenerators-website/node_modules/feedr/node_modules/js-yaml/lib/js-yaml/loader.js:1064:9)
  at composeNode (/home/travis/build/bevry/staticsitegenerators-website/node_modules/feedr/node_modules/js-yaml/lib/js-yaml/loader.js:1327:12)
  at readBlockSequence (/home/travis/build/bevry/staticsitegenerators-website/node_modules/feedr/node_modules/js-yaml/lib/js-yaml/loader.js:923:5)
  at composeNode (/home/travis/build/bevry/staticsitegenerators-website/node_modules/feedr/node_modules/js-yaml/lib/js-yaml/loader.js:1326:12)
  at readDocument (/home/travis/build/bevry/staticsitegenerators-website/node_modules/feedr/node_modules/js-yaml/lib/js-yaml/loader.js:1490:3)
  at loadDocuments (/home/travis/build/bevry/staticsitegenerators-website/node_modules/feedr/node_modules/js-yaml/lib/js-yaml/loader.js:1546:5)
  at Object.load (/home/travis/build/bevry/staticsitegenerators-website/node_modules/feedr/node_modules/js-yaml/lib/js-yaml/loader.js:1563:19)
  at module.exports.yaml.parse (/home/travis/build/bevry/staticsitegenerators-website/node_modules/feedr/out/lib/plugins.js:82:37)
  at generateParser (/home/travis/build/bevry/staticsitegenerators-website/node_modules/feedr/out/lib/feedr.js:246:16)
  at Request._callback (/home/travis/build/bevry/staticsitegenerators-website/node_modules/feedr/out/lib/feedr.js:474:18)
  at Request.self.callback (/home/travis/build/bevry/staticsitegenerators-website/node_modules/feedr/node_modules/request/request.js:198:22)
  at emitTwo (events.js:87:13)
  at Request.emit (events.js:172:7)
  at Request.<anonymous> (/home/travis/build/bevry/staticsitegenerators-website/node_modules/feedr/node_modules/request/request.js:1035:10)
  at emitOne (events.js:82:20)
  at Request.emit (events.js:169:7)
  at IncomingMessage.<anonymous> (/home/travis/build/bevry/staticsitegenerators-website/node_modules/feedr/node_modules/request/request.js:962:12)
  at emitNone (events.js:72:20)
  at IncomingMessage.emit (events.js:166:7)
  at endReadableNT (_stream_readable.js:893:12)
  at doNTCallback2 (node.js:429:9)
  at process._tickDomainCallback (node.js:384:17)

**Comment by balupton** [comment]
Should be fixed now. Thanks a lot for the report.

**Comment by lexoyo** [comment]
:+1:
